[build]
  publish = "public"
  command = "yarn build"
  functions = "functions"

[context.production]
  environment= { GATSBY_ALGOLIA_INDEX_PREFIX = "live_" }

[context.deploy-preview]
  command = "yarn build-preview"
  environment = {DEV_ENVIRONMENT_VARIABLE_FILE = "false", ALGOLIA_ADMIN_KEY = "d36bbc66-8441-49cd-8737-7e2ec33d05ae", CTP_GITHUB_API_BUILD_TOKEN="lisqf66566d00bb76f6e6a1Q4a358d3742b98pip", CTP_GITHUB_API_BUILD_KEY="pisqf66566d00bb76f6e6a1Q4a358d3742b98rop"}

[[redirects]]
  from = "/api/v1/*"
  to = "https://api.covidtracking.com/v1/:splat"
  status = 301
  force = true
  headers = {Access-Control-Allow-Origin = "*"}
  
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/images/race-dashboard/*"
  [headers.values]
  cache-control = '''
    max-age=3600,
    no-cache,
    no-store,
    must-revalidate'''
